FROM ruby:2.3.3

RUN apt-get update && apt-get install -y build-essential git libpq-dev libopencc-dev opencc libxml2-dev graphicsmagick libxslt1-dev --no-install-recommends && rm -rf /var/lib/apt/lists/*
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash - && apt-get install -y nodejs
RUN npm install -g yarn
